version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
#        auth:
#          username: mydockerhub-user
#          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo 'hello world'
      - run: ./script/install_lambdas
