version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-s3: circleci/aws-s3@2.0.0
  terraform: circleci/terraform@1.0.2

jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install xxd zip
      - run: chmod +x ./script/install_lambdas
      - run: ./script/install_lambdas
      - persist_to_workspace:
          root: /tmp/persist
          paths:
            - zipped_lambdas
  upload-lambda-src-2-s3:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/persist
      - run: ls -ahl /tmp/persist/zipped_lambdas
      - aws-s3/sync:
          from: /tmp/persist/zipped_lambdas
          to: 's3://receipt-archive-src/zipped_lambdas'
  terraform:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: terraform
      - terraform/validate:
          path: terraform
#      - terraform/fmt:
#          path: terraform
      - terraform/plan:
          path: terraform
      - terraform/apply:
          path: terraform

workflows:
  build_and_deploy:
    jobs:
      - build
      - upload-lambda-src-2-s3:
          requires:
            - build
      - terraform:
          requires:
            - upload-lambda-src-2-s3
